export const LETTER_WEIGHTS: Array<{ letter: string; weight: number }> = [
  { letter: 'A', weight: 10 },
  { letter: 'E', weight: 10 },
  { letter: 'İ', weight: 9 },
  { letter: 'L', weight: 8 },
  { letter: 'R', weight: 8 },
  { letter: 'N', weight: 8 },

  { letter: 'K', weight: 6 },
  { letter: 'M', weight: 6 },
  { letter: 'T', weight: 6 },
  { letter: 'S', weight: 6 },
  { letter: 'Y', weight: 6 },
  { letter: 'D', weight: 5 },

  { letter: 'I', weight: 5 },
  { letter: 'O', weight: 5 },
  { letter: 'U', weight: 4 },
  { letter: 'B', weight: 4 },
  { letter: 'C', weight: 3 },
  { letter: 'Ç', weight: 3 },
  { letter: 'Ş', weight: 3 },
  { letter: 'H', weight: 3 },
  { letter: 'P', weight: 3 },
  { letter: 'G', weight: 3 },
  { letter: 'Z', weight: 2 },
  { letter: 'Ü', weight: 2 },
  { letter: 'Ö', weight: 2 },

  { letter: 'J', weight: 1 },
  { letter: 'Ğ', weight: 1 },
  { letter: 'F', weight: 1 },
  { letter: 'V', weight: 1 },
];